language: scala

scala:
  - 2.12.8
  - 2.13.0

jdk:
  - oraclejdk8

before_install:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash
    etc/decrypt-keys.sh; fi
  - export PATH=${PATH}:./vendor/bundle
install:
  - rvm use 2.6.0 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1
script:
  - sbt compile
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash
    etc/publishMicrosite.sh; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then echo "Not in master branch, skipping
    deploy and release"; fi

deploy:
  - provider: script
    script: sbt compile
    #"; project core; +publishSigned; sonatypeReleaseAll; project sqs; +publishSigned; sonatypeReleaseAll;"
    on:
      tags: true

      #stages:
      #  - before_install
      #  - install
      #  - script
      #  - after_success
      #  - name: deploy
      #    if: tag IS present
